### ISSUE TITLE
mirrorFileFormat description mixed up

### ISSUE THREAD

**Issue by m11tch** [esetuk/mirrortoolconfigurator#60]
there seems to be an error in the mirrorFileFormat description though: 

 
![image](https://user-images.githubusercontent.com/5503199/167875096-21b5d47d-7eef-47c2-9b5f-9e2ef9ce01ce.png)

As it is the other way around. (dll for 6.6 and later, dat for 6.5 and older), which is also mentioned on the help page: 
 
![image](https://user-images.githubusercontent.com/5503199/167875041-b5191d3d-4287-4678-bd86-9787390fe193.png)

**Comment by esetuk** [comment]
good spot m11tch, i'll get this updated ASAP, thanks
